version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_container
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_nginx_container
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
